### ISSUE TITLE
该换许可证吧

### ISSUE THREAD

**Issue by LXYan2333** [sedgwickz/new_v2ex#1]
看宣传帖子里“请勿商用”，就别用MIT许可证了呗……

**Comment by sedgwickz** [comment]
这个问题吧，既然开源了，就很难防小人，请勿商用，算是一种君子约定吧，至于遵守不遵守感觉作为开源项目本身就难去把控商业使用这一块，这个小项目其实核心在于数据，而数据嘛，真有心者想拿到完全可以从v2ex搞，不需要依赖这个项目，so 使用MIT协议感觉没啥不妥，你拿过去改下数据源，改改样式自己用，不需要告诉我，我也不会追究你的任何责任。

下面再贴一张阮老师的开源协议图，似乎没有啥合适的协议可以很好杜绝商用吧。。。

![](https://www.ruanyifeng.com/blogimg/asset/201105/bg2011050101.png)
