### ISSUE TITLE
寻求商务合作

### ISSUE THREAD

**Issue by specialzxw** [sedgwickz/new_v2ex#2]
您好，我们对您写的这个项目非常感兴趣，想与您进行商务合作，请问是否可以留下您的邮箱或微信呢？期待您的回复。

**Comment by sedgwickz** [comment]
微信：sedgwickz

**Comment by specialzxw** [comment]
我刚刚搜索您的微信，显示用户不存在，是否是您上面留下的微信号有误呢？

**Comment by sedgwickz** [comment]
> 我刚刚搜索您的微信，显示用户不存在，是否是您上面留下的微信号有误呢？

哦，隐私设置问题，更改了，你再试一下

**Comment by specialzxw** [comment]
好了，已经添加您了~您注意通过一下~
